services:
  sql_server:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    container_name: sfers_db 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD} 
    ports: 
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  webapp:
    build: .
    container_name: sfers_webapp
    depends_on:
      - sql_server
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__SFERS_Db: "Server=sql_server,1433;Database=sfers_db;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"


volumes:
  sql_data:
